server: 
  port: 8088
  servlet:
    context-path: /redis
  tomcat:
    uri-encoding: UTF-8
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc: 
    view:
      prefix: classpath:/templates/
      suffix: .ftl
      
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # 设置数据库索引为0 默认为0
    password: # 密码为空
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
    timeout: 2000 # 连接超时时间（毫秒）
    
#mybatis配置
mybatis:
  type-aliases-package: com.fastech.entity
  mapper-locations: classpath:mybatis/*.xml
